"project_id_env": 834156
"api_token_env": "84079ca8898375f652f3723b83c4da9cbdefdcd551841902bafa2341fc518efb686878a66ebb3f60"
"api_token": "84079ca8898375f652f3723b83c4da9cbdefdcd551841902bafa2341fc518efb686878a66ebb3f60"
"base_path": "."

"preserve_hierarchy": true

"files": [
  {
    "source": "Vocable/**/*.xcstrings",
    "ignore": [
      "CrowdinExport"
    ],
    "translation": "CrowdinExport/%osx_locale%/%file_name%.xliff"
  }
]

"bundles": [
  13
]
