name: 'Run Lane'
description: 'Run a fastane lane and upload artifacts'
inputs:
  lane:
    description: 'Name of fastlane lane to run'
    required: true
runs:
  using: 'composite'
  steps:
    - name: 'Run fastlane'
      uses: actions/checkout@v4
    - run: fastlane ${{ inputs.lane }}
      shell: sh
      env:
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}

  # TODO: Artifacts
