name: Xliff Export
description: Commit translation file if changed
runs:
  using: composite
  steps:
    - name: Run lane xliff_export
      uses: ./.github/workflows/actions/run_lane
      with:
        lane: xliff_export

    - name: Diff xliff and commit if changed
      uses: actions/checkout@v4
    - run: |
        git config user.name "Localization Bot"
        git config user.email "localization_bot@willowtreeapps.com"
        git add -A
        git diff-index --quiet HEAD || git commit -m "Updated app localizations for Crowdin Export [ci skip]"
        git push --quiet
      shell: sh
