name: 'Xliff Import'
description: 'Runs the xliff_import lane after pulling'
runs:
  using: 'composite'
  steps:
      - name: 'Pull latest develop'
        uses: actions/checkout@v4
      - run: 'git pull --no-commit -q origin develop --no-rebase'
        shell: sh

      - name: 'Run lane xliff_import'
        uses: ./.github/workflows/actions/run_lane
        with:
          lane: "xliff_import"
