name: Pull Translations From Crowdin

on:
  push:
    branches:
      - develop
  workflow_dispatch:  # Keeping this for manual triggers when needed

jobs:
  synchronize-with-crowdin:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Crowdin Action
        uses: crowdin/github-action@v1
        with:
          upload_sources: true  # Upload new source strings to Crowdin
          upload_translations: false
          download_translations: true
          download_language: all
          export_only_approved: true
          localization_branch_name: crowdin/update-translations-bot
          create_pull_request: false
          push_translations: false
          crowdin_branch_name: develop
          config: 'crowdin.yml'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

      - name: Import XLIFFs to project
        uses: ./.github/workflows/actions/run_lane
        with:
          lane: xliff_import

      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        if: steps.git-check.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.CROWDIN_PR_BOT_TOKEN }}
          commit-message: Update Localizations
          branch: crowdin/update-translations-bot
          base: develop
          delete-branch: true
          title: '[CI] Update Localizations'
          body: 'Automated localization update from Crowdin'
          labels: |
            localization
            automated
