name: Pull Translations From Crowdin

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  download-translations:
    runs-on: ubuntu-latest  # Changed from macos-14 to ubuntu-latest
    environment: CrowdinAction
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test Crowdin API Connection
        run: |
          echo "Testing Crowdin API Connection..."
          response=$(curl -s -o /dev/null -w "%{http_code}" -X GET "https://api.crowdin.com/api/v2/projects/${{ vars.CROWDIN_PROJECT_ID }}" \
          -H "Authorization: Bearer ${{ secrets.CROWDIN_PERSONAL_TOKEN }}" \
          -H "Content-Type: application/json")
          echo "HTTP Response Code: $response"
          echo "token used: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}"
          if [ "$response" = "200" ]; then
            echo "API Connection Successful!"
          else
            echo "API Connection Failed!"
            exit 1
          fi
      - name: Install yq
        run: |
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod a+x /usr/local/bin/yq

      - name: Transform crowdin.yml
        run: |
          yq eval '.project_id_env = "!!int \(.project_id_env)"' crowdin.yml > crowdin_updated.yml
          mv crowdin_updated.yml crowdin.yml

      - name: Crowdin Action
        uses: crowdin/github-action@v2
        with:
          upload_sources: true
          upload_translations: false
          download_translations: true
          export_only_approved: true
          localization_branch_name: crowdin/update-translations-bot
          create_pull_request: true
          push_translations: false
          crowdin_branch_name: develop
          config: 'crowdin.yml'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ fromJSON(vars.CROWDIN_PROJECT_ID) }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code || echo "changes=true" >> $GITHUB_OUTPUT

  process-translations:
    needs: download-translations
    runs-on: macos-14  # Keep macOS runner for iOS-specific tasks
    if: needs.download-translations.outputs.changes == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up Ruby environment
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.1
          
      - name: Install bundler
        run: gem install bundler
            
      - name: Install dependencies
        run: bundle install

      - name: Import XLIFFs to project
        uses: ./.github/workflows/actions/run_lane
        with:
          lane: xliff_import

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.CROWDIN_PR_BOT_TOKEN }}
          commit-message: Update Localizations
          branch: crowdin/update-translations-bot
          base: develop
          delete-branch: true
          title: '[CI] Update Localizations'
          body: 'Automated localization update from Crowdin'
          labels: |
            localization
            automated
