name: On crowdin push
on:
  push:
    branches:
      - crowdin.**
jobs:
  on_crowdin_push:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: xliff_import
        uses: ./.github/workflows/actions/xliff_import

      - name: test_unit_ui
        uses: ./.github/workflows/actions/run_lane
        with:
          lane: test_unit_ui
          match_password: ${{ secrets.MATCH_PASSWORD }}
