name: On crowdin push
on:
  push:
    branches:
      - crowdin.**
jobs:
  on_crowdin_push:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: Integrate latest XLIFF files with project
        uses: ./.github/workflows/actions/xliff_import

      - name: Run Unit and UI tests
        uses: ./.github/workflows/actions/run_lane
        with:
          lane: test_unit_ui
          match_password: ${{ secrets.MATCH_PASSWORD }}
