name: On crowdin push
on:
  pull_request:
    branches:
      - 'crowdin.**'
jobs:
  on_crowdin_push:
    runs-on: macos-14
    steps:
      - name: 'xliff_import'
        uses: ./.github/workflows/helpers/run_lane.yml
        with:
          lane: 'xliff_import'

      - name: 'test_unit_ui'
        uses: ./.github/workflows/helpers/run_lane.yml
        with:
          lane: 'test_unit_ui'
