name: On pull request
on:
  pull_request:
    branches:
      - 'develop'
jobs:
  on_pull_request:
    runs-on: macos-14
    steps:
      - name: "test_unit_ui"
        uses: ./.github/workflows/helpers/run_lane.yml
        with:
          lane: "test_unit_ui"

      - name: "xliff_export"
        uses: ./.github/workflows/helpers/run_lane.yml
        with:
          lane: "xliff_export"
