name: 'On pull request'
on:
  pull_request:
    branches:
      - 'develop'
jobs:
  on_pull_request:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: 'test_unit_ui'
        uses: ./.github/workflows/actions/run_lane
        with:
          lane: 'test_unit_ui'

      - name: 'xliff_export'
        uses: ./.github/workflows/actions/xliff_export
